[package]
name = "typesafe_ints"
version = "0.1.0"
authors = ["jade <crates@lfcode.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
