[package]
name = "mu_shared"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typesafe_ints = { path = "../typesafe_ints" }
