[package]
name = "spanner"
version = "0.1.0"
edition = "2018"

[features]
std = []
default = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
